# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:/git/AxisChat/ui/chat.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatWidget(object):
    def setupUi(self, ChatWidget):
        ChatWidget.setObjectName("ChatWidget")
        ChatWidget.resize(929, 584)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ChatWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sideWidget = QtWidgets.QWidget(ChatWidget)
        self.sideWidget.setMinimumSize(QtCore.QSize(60, 0))
        self.sideWidget.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sideWidget.setStyleSheet("QWidget#sideWidget {\n"
"background-color: rgb(0, 118, 177);\n"
"}\n"
"")
        self.sideWidget.setObjectName("sideWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.sideWidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_7 = QtWidgets.QWidget(self.sideWidget)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 120))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 120))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_8.setContentsMargins(6, 6, 6, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        self.label_3.setMinimumSize(QtCore.QSize(48, 48))
        self.label_3.setMaximumSize(QtCore.QSize(48, 48))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/head/resource/head/head.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.verticalLayout_10.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.sideWidget)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_8.setObjectName("widget_8")
        self.toolButton_7 = QtWidgets.QToolButton(self.widget_8)
        self.toolButton_7.setGeometry(QtCore.QRect(9, 24, 36, 36))
        self.toolButton_7.setMinimumSize(QtCore.QSize(36, 36))
        self.toolButton_7.setMaximumSize(QtCore.QSize(36, 36))
        self.toolButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/button/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon)
        self.toolButton_7.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_7.setAutoRaise(True)
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_5 = QtWidgets.QToolButton(self.widget_8)
        self.toolButton_5.setGeometry(QtCore.QRect(9, 81, 36, 36))
        self.toolButton_5.setMinimumSize(QtCore.QSize(36, 36))
        self.toolButton_5.setMaximumSize(QtCore.QSize(36, 36))
        self.toolButton_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resource/button/friend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon1)
        self.toolButton_5.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(self.widget_8)
        self.toolButton_6.setGeometry(QtCore.QRect(9, 138, 36, 36))
        self.toolButton_6.setMinimumSize(QtCore.QSize(36, 36))
        self.toolButton_6.setMaximumSize(QtCore.QSize(36, 36))
        self.toolButton_6.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resource/button/group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon2)
        self.toolButton_6.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.widget_10 = QtWidgets.QWidget(self.widget_8)
        self.widget_10.setGeometry(QtCore.QRect(0, 80, 61, 41))
        self.widget_10.setMinimumSize(QtCore.QSize(36, 36))
        self.widget_10.setMaximumSize(QtCore.QSize(777, 777))
        self.widget_10.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.widget_10.setObjectName("widget_10")
        self.widget_10.raise_()
        self.toolButton_7.raise_()
        self.toolButton_5.raise_()
        self.toolButton_6.raise_()
        self.verticalLayout_10.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.sideWidget)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_10.addWidget(self.widget_9)
        self.horizontalLayout.addWidget(self.sideWidget)
        self.line_5 = QtWidgets.QFrame(ChatWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.leftWidget = QtWidgets.QWidget(ChatWidget)
        self.leftWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.leftWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.leftWidget.setStyleSheet("QWidget#leftWidget {\n"
"#background-color: rgb(0, 118, 177);\n"
"}\n"
"")
        self.leftWidget.setObjectName("leftWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.leftWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.searchWidget = QtWidgets.QWidget(self.leftWidget)
        self.searchWidget.setMinimumSize(QtCore.QSize(0, 44))
        self.searchWidget.setMaximumSize(QtCore.QSize(16777215, 44))
        self.searchWidget.setStyleSheet("QWidget#searchWidget{\n"
"background-color: rgb(220, 220, 220);\n"
"}")
        self.searchWidget.setObjectName("searchWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.searchWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBox = QtWidgets.QComboBox(self.searchWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 26))
        self.comboBox.setEditable(True)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_6.addWidget(self.searchWidget)
        self.widget_3 = QtWidgets.QWidget(self.leftWidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.friendWIdget = QtWidgets.QListWidget(self.widget_4)
        self.friendWIdget.setStyleSheet("QListWidget#friendWIdget{\n"
"background-color: rgb(220, 220, 220);\n"
"}")
        self.friendWIdget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.friendWIdget.setObjectName("friendWIdget")
        self.verticalLayout_9.addWidget(self.friendWIdget)
        self.verticalLayout_7.addWidget(self.widget_4)
        self.leftBottomWidget = QtWidgets.QWidget(self.widget_3)
        self.leftBottomWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.leftBottomWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leftBottomWidget.setStyleSheet("QWidget#leftBottomWidget{\n"
"background-color: rgb(220, 220, 220);\n"
"}")
        self.leftBottomWidget.setObjectName("leftBottomWidget")
        self.verticalLayout_7.addWidget(self.leftBottomWidget)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.leftWidget)
        self.line_4 = QtWidgets.QFrame(ChatWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.rightWidget = QtWidgets.QWidget(ChatWidget)
        self.rightWidget.setStyleSheet("QWidget#rightWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.rightWidget.setObjectName("rightWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rightWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topWidget = QtWidgets.QWidget(self.rightWidget)
        self.topWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.topWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.topWidget.setStyleSheet("")
        self.topWidget.setObjectName("topWidget")
        self.label = QtWidgets.QLabel(self.topWidget)
        self.label.setGeometry(QtCore.QRect(10, 3, 70, 70))
        self.label.setMinimumSize(QtCore.QSize(70, 70))
        self.label.setMaximumSize(QtCore.QSize(70, 70))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/head/resource/head/head.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.topWidget)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 191, 21))
        self.label_2.setStyleSheet("font: 75 11pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.toolButton_4 = QtWidgets.QToolButton(self.topWidget)
        self.toolButton_4.setGeometry(QtCore.QRect(100, 40, 71, 32))
        self.toolButton_4.setMinimumSize(QtCore.QSize(0, 32))
        self.toolButton_4.setMaximumSize(QtCore.QSize(16777214, 32))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resource/button/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName("toolButton_4")
        self.widget_6 = QtWidgets.QWidget(self.topWidget)
        self.widget_6.setGeometry(QtCore.QRect(560, 50, 131, 30))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dateLabel = QtWidgets.QLabel(self.widget_6)
        self.dateLabel.setObjectName("dateLabel")
        self.horizontalLayout_4.addWidget(self.dateLabel)
        self.verticalLayout.addWidget(self.topWidget)
        self.line = QtWidgets.QFrame(self.rightWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.bottomWidget = QtWidgets.QWidget(self.rightWidget)
        self.bottomWidget.setStyleSheet("")
        self.bottomWidget.setObjectName("bottomWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottomWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chatWidget = QtWidgets.QWidget(self.bottomWidget)
        self.chatWidget.setStyleSheet("")
        self.chatWidget.setObjectName("chatWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.chatWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outputWidget = QtWidgets.QWidget(self.chatWidget)
        self.outputWidget.setStyleSheet("")
        self.outputWidget.setObjectName("outputWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.outputWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.outputTextEdit = QtWidgets.QPlainTextEdit(self.outputWidget)
        self.outputTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.outputTextEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputTextEdit.setLineWidth(0)
        self.outputTextEdit.setReadOnly(True)
        self.outputTextEdit.setObjectName("outputTextEdit")
        self.verticalLayout_4.addWidget(self.outputTextEdit)
        self.verticalLayout_3.addWidget(self.outputWidget)
        self.line_3 = QtWidgets.QFrame(self.chatWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.inputWidget = QtWidgets.QWidget(self.chatWidget)
        self.inputWidget.setMinimumSize(QtCore.QSize(0, 130))
        self.inputWidget.setMaximumSize(QtCore.QSize(16777215, 130))
        self.inputWidget.setStyleSheet("")
        self.inputWidget.setObjectName("inputWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inputWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chatToolWidget = QtWidgets.QWidget(self.inputWidget)
        self.chatToolWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.chatToolWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chatToolWidget.setStyleSheet("")
        self.chatToolWidget.setObjectName("chatToolWidget")
        self.toolButton = QtWidgets.QToolButton(self.chatToolWidget)
        self.toolButton.setGeometry(QtCore.QRect(10, 0, 30, 30))
        self.toolButton.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resource/button/emoj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.chatToolWidget)
        self.toolButton_2.setGeometry(QtCore.QRect(50, 0, 30, 30))
        self.toolButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resource/button/font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon5)
        self.toolButton_2.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.chatToolWidget)
        self.toolButton_3.setGeometry(QtCore.QRect(90, 0, 30, 30))
        self.toolButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resource/button/screens.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon6)
        self.toolButton_3.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout_2.addWidget(self.chatToolWidget)
        self.inputTextEdit = QtWidgets.QPlainTextEdit(self.inputWidget)
        self.inputTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inputTextEdit.setLineWidth(0)
        self.inputTextEdit.setObjectName("inputTextEdit")
        self.verticalLayout_2.addWidget(self.inputTextEdit)
        self.widget = QtWidgets.QWidget(self.inputWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.closeButton = QtWidgets.QPushButton(self.widget)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.sendButton = QtWidgets.QPushButton(self.widget)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_3.addWidget(self.sendButton)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_3.addWidget(self.inputWidget)
        self.horizontalLayout_2.addWidget(self.chatWidget)
        self.line_2 = QtWidgets.QFrame(self.bottomWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.infoWidget = QtWidgets.QWidget(self.bottomWidget)
        self.infoWidget.setMinimumSize(QtCore.QSize(140, 0))
        self.infoWidget.setMaximumSize(QtCore.QSize(140, 16777215))
        self.infoWidget.setStyleSheet("")
        self.infoWidget.setObjectName("infoWidget")
        self.horizontalLayout_2.addWidget(self.infoWidget)
        self.verticalLayout.addWidget(self.bottomWidget)
        self.horizontalLayout.addWidget(self.rightWidget)

        self.retranslateUi(ChatWidget)
        QtCore.QMetaObject.connectSlotsByName(ChatWidget)

    def retranslateUi(self, ChatWidget):
        _translate = QtCore.QCoreApplication.translate
        ChatWidget.setWindowTitle(_translate("ChatWidget", "Form"))
        self.label_2.setText(_translate("ChatWidget", "聊天对象名称 (他的数字ID)"))
        self.toolButton_4.setText(_translate("ChatWidget", "文件"))
        self.dateLabel.setText(_translate("ChatWidget", "2020/04/03 22:22:33"))
        self.closeButton.setText(_translate("ChatWidget", "关闭"))
        self.sendButton.setText(_translate("ChatWidget", "发送"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChatWidget = QtWidgets.QWidget()
    ui = Ui_ChatWidget()
    ui.setupUi(ChatWidget)
    ChatWidget.show()
    sys.exit(app.exec_())
